parameters:
  - $ref: ../components/parameters/applicationID.yaml
get:
  tags:
    - Applications
  summary: Get an application
  description: Retrieve an existing application with its ID.
  operationId: getApplication
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Temporal.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '402':
      $ref: ../components/responses/RequestFailed.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '429':
      $ref: ../components/responses/TooManyRequests.yaml
    '500':
      $ref: ../components/responses/ServerError.yaml
delete:
  tags:
    - Applications
  summary: Delete an application
  description: Delete an application
  operationId: deleteApplication
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Temporal.yaml
  responses:
    '200':
      description: OK
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '402':
      $ref: ../components/responses/RequestFailed.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      $ref: ../components/responses/Conflict.yaml
    '429':
      $ref: ../components/responses/TooManyRequests.yaml
    '500':
      $ref: ../components/responses/ServerError.yaml
