get:
  tags:
    - Applications
  summary: List Applications
  description: >-
    Returns a list of all your applications sorted chronologicaly by creation
    date.
  operationId: listApplications
  parameters:
    - $ref: ../components/parameters/limit.yaml
    - $ref: ../components/parameters/offset.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/Temporal.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '402':
      $ref: ../components/responses/RequestFailed.yaml
    '429':
      $ref: ../components/responses/TooManyRequests.yaml
    '500':
      $ref: ../components/responses/ServerError.yaml
post:
  tags:
    - Applications
  summary: Create an application
  description: Creates a new application
  operationId: createApplication
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Temporal.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Temporal.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '402':
      $ref: ../components/responses/RequestFailed.yaml
    '429':
      $ref: ../components/responses/TooManyRequests.yaml
    '500':
      $ref: ../components/responses/ServerError.yaml
