parameters:
  - $ref: ../components/parameters/applicationID.yaml
get:
  tags:
    - Applications
  summary: Get an application
  description: Retrieve an existing application with its ID.
  operationId: getApplication
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Temporal.yaml
    "400":
      $ref: ../components/responses/EBadRequest.yaml
    "401":
      $ref: ../components/responses/EUnauthorized.yaml
    "402":
      $ref: ../components/responses/ERequestFailed.yaml
    "404":
      $ref: ../components/responses/ENotFound.yaml
    "429":
      $ref: ../components/responses/ETooManyRequests.yaml
    "500":
      $ref: ../components/responses/EServerError.yaml
delete:
  tags:
    - Applications
  summary: Delete an application
  description: Delete an application
  operationId: deleteApplication
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Temporal.yaml
  responses:
    "200":
      description: OK
    "400":
      $ref: ../components/responses/EBadRequest.yaml
    "401":
      $ref: ../components/responses/EUnauthorized.yaml
    "402":
      $ref: ../components/responses/ERequestFailed.yaml
    "404":
      $ref: ../components/responses/ENotFound.yaml
    "409":
      $ref: ../components/responses/EConflict.yaml
    "429":
      $ref: ../components/responses/ETooManyRequests.yaml
    "500":
      $ref: ../components/responses/EServerError.yaml
